
name: create a mirror of website and zip the saved contents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mirror-website:
    name: mirrors the website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O book.html https://homebrewery.naturalcrit.com/share/J7Y1--Z7ZWIY
